### ISSUE TITLE
v1.0.2 x86 falls while loading in Far x86 5858

### ISSUE THREAD

**Issue by dmitrybarabash** [alabuzhev/unicon#1]
The error message is "NtQueryInformationProcess".

**Comment by alabuzhev** [comment]
OS?

**Comment by dmitrybarabash** [comment]
> OS?

Windows 10 Pro 21H1 x64

**Comment by alabuzhev** [comment]
conhost.exe is 64-bit in x64 OS, so the injected code must also be 64-bit.
The x86 plugin running under WOW64 can do it only by creating a new 64-bit process, loading the x64 plugin into it and delegating the work to that process.
While that's technically doable, I don't plan to implement that, because you can easily do that yourself - just run the provided 64-bit exe from Far, manually or from some startup lua script.

I'll update the error message at some point to make this more obvious.

**Comment by alabuzhev** [comment]
In 1.0.3 it will look like this:

![image](https://user-images.githubusercontent.com/11453922/129942441-4d1e1998-a171-4e1e-a041-81a65e0468da.png)
